@startuml APP测试鉴权-权限验证
actor "User" as user
participant "Android APP" as app
participant "Server" as server
participant "MySQL" as db
user->app:启动APP
app->app:登录/登录态校验通过
app->server:请求更新用户信息
app->server:更新用户信息，获取业务信息\nPOST /updateAccount
server->db:查询用户测试权限
server<-db:返回数据
server->server:……\n将测试权限封装到业务数据中
app<-server:返回业务数据
app->app:解析业务数据\n检查测试权限
alt 无权限
app->app:弹窗提示用户
else
app->app:进入主页\n……
end
user<--app
@enduml